api_id = "27433400"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #)<@scaMmEr<
api_hash = "1a286620de5ffe0a7d9b57e604293555"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               #)sCaMMER^
bot_token = "8280702030:AAFCQiW2ZhpfiAxpdAlEyW8FmW32zO5Wa28"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #-=(ScAMMeR>
FORCE_CHANNEL = 'Source'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #@_&ScAMmeR#<+
LOGS_CHANNEL =  -1003635671191                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          #^ScAmmeR%%*
OWNER = 6201066540                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #$^sCAmMer_
image = 'logo.jpg'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #(SCammER-
MONGO_URI = 'mongodb+srv://niravpatel180503_db_user:vjWNaWhRk0gMSNyQ@cluster0.26bfgmf.mongodb.net/?appName=Cluster0'
OWNER_USERNAME = 'Uploaderforwardbotbot'

START_TEXT="""
I'm Batch-Txt Extractor bot....!

🚀 Made By blackheart.ex🚀

Usage : First select the app listed below. ⤵️
"""
START_TEXT1="""
I'm Batch-Txt Extractor bot....!

🎯 Made By blackheart.ex 🎯
🔰  Now, select the course listed below. 📌
"""
START_TEXTCP="""
I'm CLASSPLUS Extractor bot....!

⤵️  Now, select the Option listed below. 🎯
"""
START_TEXTAPPX="""
I'm APPX Extractor bot....!

🔰  Now, select the Option listed below. 🎯
"""
START_TEXTCP1="""
I'm Going to Generate Auth Token....!

🎯  Now, select the Methods to Geneterate Classplus Auth Token. ✅
"""
HELP_TEXT="""
I'm Batch extractor bot...!
🚀Commands

/helper - For Extracting Txts.

⚠️ Save this id » @sakshambhaiya in case of Copyright infringement.
"""



